import type { Artifact, HumanApproval, Run, RunEvent, RunStatus } from '@agent-flow/contracts';

/**
 * In-memory runtime state used by the mock API for deterministic demos.
 */
const runs = new Map<string, Run>();
const events = new Map<string, RunEvent[]>();
const approvals = new Map<string, HumanApproval>();
const artifacts = new Map<string, Artifact[]>();

/**
 * Generates timestamps at mutation time so event order remains visible in tests and demos.
 */
function getCurrentTimestamp() {
  return new Date().toISOString();
}

function createId(prefix: string) {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
}

function createRunEvent(
  runId: string,
  sequence: number,
  payload: Omit<RunEvent, 'id' | 'runId' | 'sequence' | 'timestamp'>
): RunEvent {
  return {
    id: `event-${runId}-${sequence}`,
    runId,
    sequence,
    timestamp: getCurrentTimestamp(),
    ...payload
  };
}

/**
 * Creates a mock run with ordered events and a pending approval gate.
 */
export function createMockRun(workflowId: string, input: string): Run {
  const runId = createId('run');
  const approvalId = createId('approval');
  const run: Run = {
    id: runId,
    workflowId,
    input,
    status: 'waiting_approval',
    startedAt: getCurrentTimestamp()
  };

  const approval: HumanApproval = {
    id: approvalId,
    runId,
    nodeId: 'approval',
    title: '确认高风险验证命令',
    description: '执行 Agent 将运行验证命令。请确认该动作符合当前任务边界。',
    status: 'pending',
    createdAt: getCurrentTimestamp()
  };

  runs.set(runId, run);
  approvals.set(approvalId, approval);
  artifacts.set(runId, []);
  // Reason: every demo run starts with enough ordered events to exercise timeline and approval surfaces.
  events.set(runId, [
    createRunEvent(runId, 1, {
      type: 'run_started',
      status: 'running',
      nodeId: 'input',
      message: `已接收任务：${input}`
    }),
    createRunEvent(runId, 2, {
      type: 'node_started',
      status: 'running',
      nodeId: 'planner',
      message: '任务规划 Agent 正在拆解目标和依赖。'
    }),
    createRunEvent(runId, 3, {
      type: 'tool_call',
      status: 'running',
      nodeId: 'research',
      message: '研究分析 Agent 正在调用知识库检索。',
      toolCall: { toolId: 'tool-search', input: { query: input } }
    }),
    createRunEvent(runId, 4, {
      type: 'tool_result',
      status: 'completed',
      nodeId: 'research',
      message: '已检索到架构、依赖和验证策略摘要。'
    }),
    createRunEvent(runId, 5, {
      type: 'human_approval',
      status: 'waiting',
      nodeId: 'approval',
      approvalId,
      message: '等待人工审批高风险验证命令。'
    })
  ]);

  return run;
}

/**
 * Lists mock runs with the newest execution first.
 */
export function listRuns(): Run[] {
  return [...runs.values()].sort((a, b) => b.startedAt.localeCompare(a.startedAt));
}

/**
 * Gets a run by id from in-memory state.
 */
export function getRun(runId: string): Run | null {
  return runs.get(runId) ?? null;
}

/**
 * Gets ordered events for a run.
 */
export function getRunEvents(runId: string): RunEvent[] {
  return events.get(runId) ?? [];
}

/**
 * Gets the current pending approval for a run.
 */
export function getPendingApproval(runId: string): HumanApproval | null {
  return [...approvals.values()].find((approval) => approval.runId === runId && approval.status === 'pending') ?? null;
}

/**
 * Lists artifacts generated by a run.
 */
export function listArtifacts(runId: string): Artifact[] {
  return artifacts.get(runId) ?? [];
}

/**
 * Updates a run status and closes terminal runs.
 */
export function updateRunStatus(runId: string, status: RunStatus): Run | null {
  const run = runs.get(runId);
  if (!run) return null;
  const updated = {
    ...run,
    status,
    endedAt: ['completed', 'failed', 'canceled'].includes(status) ? getCurrentTimestamp() : run.endedAt
  };
  runs.set(runId, updated);
  return updated;
}

/**
 * Cancels a run and appends a cancellation event.
 */
export function cancelRun(runId: string): Run | null {
  const run = updateRunStatus(runId, 'canceled');
  if (!run) return null;
  const current = getRunEvents(runId);
  current.push(
    createRunEvent(runId, current.length + 1, {
      type: 'run_canceled',
      status: 'canceled',
      message: '用户取消了当前运行。'
    })
  );
  events.set(runId, current);
  return run;
}

/**
 * Applies an approval decision and finalizes the run.
 */
export function submitHumanDecision(runId: string, decision: 'approved' | 'rejected', note?: string): Run | null {
  const approval = getPendingApproval(runId);
  const run = runs.get(runId);
  if (!approval || !run) return null;

  approvals.set(approval.id, {
    ...approval,
    status: decision,
    decidedAt: getCurrentTimestamp(),
    note
  });

  const current = getRunEvents(runId);
  current.push(
    createRunEvent(runId, current.length + 1, {
      type: 'human_decision',
      status: decision === 'approved' ? 'completed' : 'failed',
      nodeId: 'approval',
      approvalId: approval.id,
      message: decision === 'approved' ? '人工审批通过，继续执行。' : '人工审批拒绝，运行终止。'
    })
  );

  if (decision === 'rejected') {
    current.push(
      createRunEvent(runId, current.length + 1, {
        type: 'run_failed',
        status: 'failed',
        message: '审批拒绝后运行失败结束。'
      })
    );
    events.set(runId, current);
    return updateRunStatus(runId, 'failed');
  }

  const artifact: Artifact = {
    id: createId('artifact'),
    runId,
    type: 'markdown',
    title: '发布检查摘要',
    content:
      '## 发布检查摘要\n\n- 任务规划完成。\n- 上下文检索完成。\n- 高风险验证已获人工批准。\n- Mock runtime 生成了可替换真实后端的事件链路。',
    createdAt: getCurrentTimestamp()
  };
  artifacts.set(runId, [artifact]);

  current.push(
    createRunEvent(runId, current.length + 1, {
      type: 'run_completed',
      status: 'completed',
      nodeId: 'output',
      message: '运行完成，已生成执行摘要。'
    }),
    createRunEvent(runId, current.length + 2, {
      type: 'artifact',
      status: 'completed',
      nodeId: 'output',
      artifactId: artifact.id,
      message: '已生成 Markdown 结果产物。'
    })
  );
  events.set(runId, current);
  return updateRunStatus(runId, 'completed');
}
